### PR TITLE
Sprint 1

### LINKED ISSUE #16: Work in feedback of Sprint 1 Code Review
- [x] Prefix private/protected members with `_`
- [x] When deleting/inserting/retrieving elements of STL containers, always use an appropriate STL method like `erase()`, `find()`, `at()` etc. ...
- [x] Use asserts where possible
- [x] Reserve vector size when you know in advance how much space you need (can be done in initializer)
- [x] Rename Loop Variables to more appropriate names (no i, j etc. ...)
- [x] Use const where possible
- [x] `StorageManager` add exception throwing in public methods
- [x] Check all `DebugAsserts()`

### PR DESCRIPTION
**Pull request by m0e33**

### CODE REVIEW

File: src/lib/storage/storage_manager.cpp [hunk 1]
```diff
@@ -10,38 +10,41 @@
...
-  return *(new StorageManager());
-  // A really hacky fix to get the tests to run - replace this with your implementation
+  static StorageManager sm;
+  return sm;
 }
 
-void StorageManager::add_table(const std::string& name, std::shared_ptr<Table> table) {
-  // Implementation goes here
-}
+void StorageManager::add_table(const std::string& name, std::shared_ptr<Table> table) { tables[name] = table; }
```
Comment (PeterTsayun) [inline src/lib/storage/storage_manager.cpp:17]:
```suggestion
void StorageManager::add_table(const std::string& name, std::shared_ptr<Table> table) {
  DebugAssert(!tables.contains(name), "A table with provided name already exists");
  tables[name] = table;  
}
```

File: src/lib/storage/storage_manager.cpp [hunk 2]
```diff
@@ -10,38 +10,41 @@
...
 
 void StorageManager::drop_table(const std::string& name) {
-  // Implementation goes here
+  if (tables.at(name) != NULL) {
```
Comment (PeterTsayun) [inline src/lib/storage/storage_manager.cpp:20]:
```suggestion
  if (tables.contains(name)) {
```
Theoretically, a situation may occur, where a `NULL` pointer was added to the `tables` (currently, there is no check for that in the `add_table` method). So, I think, the check with `contains` could be more robust.

File: src/lib/storage/chunk.cpp [hunk 3]
```diff
@@ -14,27 +14,45 @@
...
 
-void Chunk::add_segment(std::shared_ptr<BaseSegment> segment) {
-  // Implementation goes here
-}
+void Chunk::add_segment(std::shared_ptr<BaseSegment> segment) { segments.push_back(segment); }
 
 void Chunk::append(const std::vector<AllTypeVariant>& values) {
-  // Implementation goes here
-}
+  DebugAssert(!values.empty(), "");
```
Comment (PeterTsayun) [inline src/lib/storage/chunk.cpp:20]:
```suggestion
  DebugAssert(!values.empty(), "Appending an empty row");
```

File: src/lib/storage/chunk.cpp [hunk 4]
```diff
@@ -14,27 +14,45 @@
...
+  DebugAssert(values.size() == segments.size(), "");
```
Comment (PeterTsayun) [inline src/lib/storage/chunk.cpp:21]:
```suggestion
  DebugAssert(values.size() == segments.size(), "Invalid number of columns to be inserted");
```

File: src/lib/storage/chunk.cpp [hunk 5]
```diff
@@ -14,27 +14,45 @@
...
-std::shared_ptr<BaseSegment> Chunk::get_segment(ColumnID column_id) const {
-  // Implementation goes here
-  return nullptr;
+  int size = segments.size();
+  for (int i = 0; i < size; i++) {
+    segments[i]->append(values[i]);
+  }
 }
 
+std::shared_ptr<BaseSegment> Chunk::get_segment(ColumnID column_id) const { return segments[column_id]; }
```
Comment (PeterTsayun) [inline src/lib/storage/chunk.cpp:29]:
```suggestion
std::shared_ptr<BaseSegment> Chunk::get_segment(ColumnID column_id) const { return segments.at(column_id); }
```
`at()` will throw an error when accessing indexes out of range

File: src/lib/storage/chunk.hpp [hunk 6]
```diff
@@ -40,8 +40,10 @@ class Chunk : private Noncopyable {
   // Returns the segment at a given position
   std::shared_ptr<BaseSegment> get_segment(ColumnID column_id) const;
 
+  void print(int col_size, std::ostream& out = std::cout) const;
+
  protected:
-  // Implementation goes here
+  std::vector<std::shared_ptr<BaseSegment>> segments;
```
Comment (PeterTsayun) [inline src/lib/storage/chunk.hpp:46]:
```suggestion
  std::vector<std::shared_ptr<BaseSegment>> _segments;
```
Identifiers of protected members should begin with an underscore :wink:

File: src/lib/storage/storage_manager.cpp [hunk 7]
```diff
@@ -10,38 +10,41 @@
...
+    tables.erase(name);
+  } else {
+    throw std::runtime_error("no such table");
+  }
 }
 
 std::shared_ptr<Table> StorageManager::get_table(const std::string& name) const {
-  // Implementation goes here
+  if (tables.at(name) != NULL) return tables.at(name);
```
Comment (PeterTsayun) [inline src/lib/storage/storage_manager.cpp:28]:
```suggestion
  if (tables.contains(name)){
    return tables.at(name);
  }
  throw std::runtime_error("No table with the provided name");
```

Same here

File: src/lib/storage/storage_manager.hpp [hunk 8]
```diff
@@ -43,7 +43,7 @@ class StorageManager : private Noncopyable {
  protected:
   StorageManager() {}
   StorageManager& operator=(StorageManager&&) = default;
-
-  // Implementation goes here
+  std::map<std::string, std::shared_ptr<Table>> tables;
```
Comment (PeterTsayun) [inline src/lib/storage/storage_manager.hpp:46]:
```suggestion
  std::map<std::string, std::shared_ptr<Table>> _tables;
```
Protected member

File: src/lib/storage/table.cpp [hunk 9]
```diff
@@ -17,57 +17,91 @@
...
 
-Table::Table(const ChunkOffset target_chunk_size) {
-  // Implementation goes here
+Table::Table(const ChunkOffset target_chunk_size) : max_chunk_size{target_chunk_size} {
+  chunks.push_back(std::make_shared<Chunk>());
 }
 
 void Table::add_column(const std::string& name, const std::string& type) {
-  // Implementation goes here
+  if (row_count() > 0) {
```
Comment (PeterTsayun) [inline src/lib/storage/table.cpp:25]:
```suggestion
  DebugAssert(row_count() == 0, "The chunk is not empty: no modification of the colyumn layout possible");
```

File: src/lib/storage/table.cpp [hunk 10]
```diff
@@ -17,57 +17,91 @@
...
 
-const std::string& Table::column_name(const ColumnID column_id) const {
-  throw std::runtime_error("Implement Table::column_name");
-}
+const std::string& Table::column_name(const ColumnID column_id) const { return col_names[column_id]; }
 
-const std::string& Table::column_type(const ColumnID column_id) const {
-  throw std::runtime_error("Implement Table::column_type");
-}
+const std::string& Table::column_type(const ColumnID column_id) const { return col_types[column_id]; }
```
Comment (PeterTsayun) [inline src/lib/storage/table.cpp:88]:
```suggestion
const std::string& Table::column_type(const ColumnID column_id) const { return col_types.at(column_id); }
```
`at()` throws an error when accessing elements out of range

File: src/lib/storage/value_segment.cpp [hunk 11]
```diff
@@ -14,18 +14,20 @@ namespace opossum {
 
 template <typename T>
 AllTypeVariant ValueSegment<T>::operator[](const ChunkOffset chunk_offset) const {
-  throw std::runtime_error("Implement ValueSegment::operator[]");
+  if (chunk_offset >= this->size()) {
+    throw std::runtime_error("Vector out of bounds");
+  }
+  return valuesVector[chunk_offset];
```
Comment (PeterTsayun) [inline src/lib/storage/value_segment.cpp:20]:
```suggestion
  return valuesVector.at(chunk_offset);
```

**Review by PeterTsayun — COMMENTED** [review]
Some minor stuff. Great work anyway :wink:

File: src/lib/storage/storage_manager.cpp (hunk 7 above)
Comment (m0e33) [reply src/lib/storage/storage_manager.cpp]: Warum sollten wir hier kein `DebugAssert()`nehmen?

File: src/lib/storage/chunk.cpp [hunk 12]
```diff
@@ -14,27 +14,45 @@
...
-  // Implementation goes here
-}
+  DebugAssert(!values.empty(), "");
+  DebugAssert(values.size() == segments.size(), "");
 
-std::shared_ptr<BaseSegment> Chunk::get_segment(ColumnID column_id) const {
-  // Implementation goes here
-  return nullptr;
+  int size = segments.size();
+  for (int i = 0; i < size; i++) {
```
Comment (Bensk1) [inline src/lib/storage/chunk.cpp]: Use descriptive names instead of `i`. Also, according to the contributing guidelines, we want to use `auto` or explicit integer types, e.g., `uint64_t` or at least `size_t`.

File: src/lib/storage/chunk.cpp [hunk 13]
```diff
@@ -14,27 +14,45 @@
...
-  // Implementation goes here
-  return 0;
+  if (segments.empty())
+    return 0;
+  else
+    return segments[0]->size();
+}
+
+void Chunk::print(int col_size, std::ostream& out) const {
+  for (ChunkOffset i = 0; i < size(); i++) {
```
Comment (Bensk1) [inline src/lib/storage/chunk.cpp:38]: Don't evaluate `size()` with every loop iteration. Similar to http://llvm.org/docs/CodingStandards.html#don-t-evaluate-end-every-time-through-a-loop

Also, again avoid using `i`.

File: src/lib/storage/chunk.hpp [hunk 14]
```diff
@@ -40,8 +40,10 @@ class Chunk : private Noncopyable {
   // Returns the segment at a given position
   std::shared_ptr<BaseSegment> get_segment(ColumnID column_id) const;
 
+  void print(int col_size, std::ostream& out = std::cout) const;
```
Comment (mweisgut) [inline src/lib/storage/chunk.hpp:44]: Be explicit with types: Use [u]int(8|16|32|64)_t instead of int, long, uint etc.

File: src/lib/storage/chunk.cpp [hunk 15]
```diff
@@ -14,27 +14,45 @@
...
+    for (auto segment : segments) {
```
Comment (Bensk1) [inline src/lib/storage/chunk.cpp]: `const auto& segment`

File: src/lib/storage/chunk.cpp [hunk 16]
```diff
@@ -14,27 +14,45 @@
...
 ChunkOffset Chunk::size() const {
-  // Implementation goes here
-  return 0;
+  if (segments.empty())
+    return 0;
+  else
+    return segments[0]->size();
+}
+
+void Chunk::print(int col_size, std::ostream& out) const {
```
Comment (mweisgut) [inline src/lib/storage/chunk.cpp:37]: Be explicit with types: Use [u]int(8|16|32|64)_t instead of int, long, uint etc.

File: src/lib/storage/storage_manager.cpp (hunk 2 above)
Comment (Bensk1) [reply src/lib/storage/storage_manager.cpp]: `nullptr` instead of `NULL`. Also, Peter is correct, `contains()` is much nicer here.

File: src/lib/storage/storage_manager.cpp [hunk 17]
```diff
@@ -10,38 +10,41 @@
...
-}
+void StorageManager::add_table(const std::string& name, std::shared_ptr<Table> table) { tables[name] = table; }
 
 void StorageManager::drop_table(const std::string& name) {
-  // Implementation goes here
+  if (tables.at(name) != NULL) {
+    tables.erase(name);
+  } else {
+    throw std::runtime_error("no such table");
+  }
```
Comment (Bensk1) [inline src/lib/storage/storage_manager.cpp]: Instead of `else... throw` assert could be used.

File: src/lib/storage/table.cpp (hunk 9 above)
Comment (Bensk1) [reply src/lib/storage/table.cpp]: This should probably even be an `Assert()`

File: src/lib/storage/table.cpp [hunk 18]
```diff
@@ -17,57 +17,91 @@
...
+    chunk->add_segment(value_segment);
+  });
 }
 
 void Table::append(const std::vector<AllTypeVariant>& values) {
-  // Implementation goes here
+  if (chunks.back()->size() == max_chunk_size) {
+    std::shared_ptr<Chunk> chunk = std::make_shared<Chunk>();
+    chunks.push_back(chunk);
+    for (auto type : col_types) {
```
Comment (Bensk1) [inline src/lib/storage/table.cpp]: `const auto&`...

File: src/lib/storage/table.cpp [hunk 19]
```diff
@@ -17,57 +17,91 @@
...
+      _add_segment_to_chunk(chunk, type);
+    }
+  }
+  chunks.back()->append(values);
 }
 
 ColumnCount Table::column_count() const {
-  // Implementation goes here
-  return ColumnCount{0};
+  u_int16_t count = col_names.size();
```
Comment (Bensk1) [inline src/lib/storage/table.cpp]: I haven't seen this type before. Is this windows specific?

File: src/lib/storage/table.cpp [hunk 20]
```diff
@@ -17,57 +17,91 @@
...
 
 ColumnID Table::column_id_by_name(const std::string& column_name) const {
-  // Implementation goes here
-  return ColumnID{0};
+  auto id = std::find(col_names.begin(), col_names.end(), column_name);
+  if (id != col_names.end()) {
+    int index = id - col_names.begin();
+    return ColumnID(index);
+  } else {
+    throw std::runtime_error("no column with this name exists");
```
Comment (Bensk1) [inline src/lib/storage/table.cpp]: See above.

File: src/lib/storage/table.cpp [hunk 21]
```diff
@@ -17,57 +17,91 @@
...
+const std::string& Table::column_type(const ColumnID column_id) const { return col_types[column_id]; }
 
-Chunk& Table::get_chunk(ChunkID chunk_id) { throw std::runtime_error("Implement Table::get_chunk"); }
+Chunk& Table::get_chunk(ChunkID chunk_id) { return *chunks[chunk_id]; }
 
-const Chunk& Table::get_chunk(ChunkID chunk_id) const { throw std::runtime_error("Implement Table::get_chunk"); }
+const Chunk& Table::get_chunk(ChunkID chunk_id) const { return *chunks[chunk_id]; }
+
+void Table::print(std::ostream& out) const {
+  int col_size = 20;
```
Comment (Bensk1) [inline src/lib/storage/table.cpp]: `constexpr`

File: src/lib/storage/storage_manager.hpp [hunk 22]
```diff
@@ -43,7 +43,7 @@ class StorageManager : private Noncopyable {
...
+  static StorageManager* instance;
```
Comment (mweisgut) [inline src/lib/storage/storage_manager.hpp]: Generally, use smart pointers rather than raw pointers. However, even a smart pointer member is not necessary here since `instance` is never used but the static local `static StorageManager sm` is used instead.

File: src/lib/storage/table.hpp [hunk 23]
```diff
@@ -71,7 +71,14 @@ class Table : private Noncopyable {
...
   void append(const std::vector<AllTypeVariant>& values);
 
+  void print(std::ostream& out = std::cout) const;
+
  protected:
-  // Implementation goes here
+  const ChunkOffset max_chunk_size;
+  std::vector<std::shared_ptr<Chunk>> chunks;
+  std::vector<std::string> col_names;
+  std::vector<std::string> col_types;
```
Comment (Bensk1) [inline src/lib/storage/table.hpp]: All of these should have a preceding `_`.

File: src/lib/storage/value_segment.cpp [hunk 24]
```diff
@@ -14,18 +14,20 @@ namespace opossum {
 
 template <typename T>
 AllTypeVariant ValueSegment<T>::operator[](const ChunkOffset chunk_offset) const {
-  throw std::runtime_error("Implement ValueSegment::operator[]");
+  if (chunk_offset >= this->size()) {
```
Comment (Bensk1) [inline src/lib/storage/value_segment.cpp]: "Don't write `this->` if you don't have to"

Comment (Bensk1) [reply src/lib/storage/value_segment.cpp]: Also, use `at()` or a `DebugAssert`

File: src/lib/storage/value_segment.hpp [hunk 25]
```diff
@@ -28,7 +28,7 @@ class ValueSegment : public BaseSegment {
   const std::vector<T>& values() const;
 
  protected:
-  // Implementation goes here
+  std::vector<T> valuesVector;
```
Comment (Bensk1) [inline src/lib/storage/value_segment.hpp]: `_values_vector`

File: src/lib/storage/value_segment.cpp (hunk 11 above)
Comment (mweisgut) [inline src/lib/storage/value_segment.cpp]: For variables, please use lowercase separated by underscores, e.g., `chunk_size`. (see `CONTRIBUTING.md`)

File: src/test/storage/table_test.cpp [hunk 26]
```diff
@@ -12,63 +12,81 @@
...
+  EXPECT_THROW(t.add_column("col_3", "string"), std::exception);
+}
+
+TEST_F(StorageTableTest, PrivateAddSegment) {
+  t.add_column("col_3", "int");
+  auto& currentChunk = t.get_chunk(ChunkID{0});
+  auto lastSegment = currentChunk.get_segment(ColumnID{2});
+  EXPECT_EQ(currentChunk.column_count(), 3u);
+  EXPECT_THROW(lastSegment->append("String"), std::exception);
+}
```
Comment (Bensk1) [inline src/test/storage/table_test.cpp:90]: Is this supposed to test that `String` cannot be added to a segment of type `int`? Then, this test should be named differently.

File: src/test/storage/table_test.cpp [hunk 27]
```diff
@@ -12,63 +12,81 @@
...
+
+TEST_F(StorageTableTest, AddColumnFail) {
+  t.append({42, "Space Traveler"});
+  EXPECT_THROW(t.add_column("col_3", "string"), std::exception);
+}
+
+TEST_F(StorageTableTest, PrivateAddSegment) {
+  t.add_column("col_3", "int");
+  auto& currentChunk = t.get_chunk(ChunkID{0});
```
Comment (mweisgut) [inline src/test/storage/table_test.cpp:86]: Please use lowercase separated by underscores, see above.

File: src/test/storage/table_test.cpp [hunk 28]
```diff
@@ -12,63 +12,81 @@
...
+  auto lastSegment = currentChunk.get_segment(ColumnID{2});
```
Comment (mweisgut) [inline src/test/storage/table_test.cpp:87]: lowercase separated by underscores, see above

File: src/test/storage/table_test.cpp (hunk 27 above)
Comment (mweisgut) [inline src/test/storage/table_test.cpp:86]: can be const
